// nextjs-crud/src/pages/index.tsx
import React from "react";

import { useRouter } from "next/router";

import Head from "atoms/Head";
import Home from "components/home/Home";

export default function fun(props) {
  const nextRouter = useRouter();

  return (
    <>
      <Head
        title={"AWS + NextJS チャット機能 | Han Sahyeon"}
        // description={"ポートフォリオ用ページです。"}
        url={nextRouter.pathname}
      />
      <Home></Home>
    </>
  );
}

// nuxtjs-home/src/pages/index.vue
<template>
  <div id="page-home">
    <Home />
  </div>
</template>

<script lang="ts">
import Vue from "vue";

import Head from "~/atoms/Head";
import Home from "~/components/home/Home.vue";

export default Vue.extend({
  head: {
    ...Head,
    title: "HAN SAHYEON（ハン・サヒャン） | ウェブ開発ポートフォリオ"
  },
  components: {
    Home
  }
});
</script>

<style lang="scss" scoped></style>
